# A07 step 04 — Statistical model (total effect)
#
# Specifies what gets fitted. Nothing is fitted here: step 05 fits priors only,
# step 07 fits the data.
#
# NOTE: rethinking must not be attached. See docs/adr/0001-brms-over-rethinking.md.

library(brms)
library(here)

DATA <- here("homework", "contributions", "A07", "total-effect", "data")
frame <- readRDS(file.path(DATA, "03_analysis_frame.rds"))
dat <- frame$dat


# ---- Formula -----------------------------------------------------------------
# Ws ~ Fs      the adjustment set for the total effect is empty, so F is the only term
#
# Term sources:
#   Fs         generative model (F -> W) and the exposure the estimand intervenes on
#   Intercept  generative model (W has a mean)
#
# Gs is deliberately ABSENT. G is a mediator, a descendant of F, and conditioning on it
# would close F -> G -> W and turn this into the direct effect — the estimand the
# ../../direct-effect/ analysis answers.
# As is deliberately ABSENT. A has no open path to W except through F, so it blocks
# nothing and adding it would only cost precision.
# No term here was added from looking at the data.

f_total <- bf(Ws ~ Fs)


# ---- Family and link ---------------------------------------------------------
# gaussian with the identity link. The outcome is standardised weight: continuous,
# unbounded on the standardised scale, symmetric, and generated by exactly this
# structure in step 02.

fam <- gaussian()


# ---- Parameters needing priors -----------------------------------------------
# What step 05 owes.

cat("\n================ STEP 04 ================\n")
cat("formula: "); print(f_total)
cat("\nparameters requiring priors:\n")
print(get_prior(f_total, data = dat, family = fam)[, c("prior", "class", "coef", "source")])


# ---- No varying effects ------------------------------------------------------
# No group-level term. Step 02 M4: an ANOVA on weight residuals after F and G gives
# F = 0.80, p = 0.75, ICC ~ 0 — there is no between-group variance to pool over.
# Parked in the README with the condition that would make it worth adding.


# ---- Nothing simplified away -------------------------------------------------
# The generative model is linear and Gaussian, and so is this formula. For the total
# effect the two match exactly: step 02's W = bFW*F + bGW*G + e, marginalised over G,
# is linear in F with slope bFW + bFG*bGW — which is the estimand, and is what the
# single Fs coefficient estimates.

saveRDS(list(formula = f_total, family = fam, dat = dat), file.path(DATA, "04_model_spec.rds"))
